source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Avoid the Hill' do
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacesAPI'
pod 'SwiftyJSON', :git => 'https://github.com/IBM-Swift/SwiftyJSON.git'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git'
pod 'AlamofireNetworkActivityIndicator', :git => 'https://github.com/Alamofire/AlamofireNetworkActivityIndicator.git'
end
